apiVersion: v1
kind: Pod
metadata:
  name: curl-with-ambassador
spec:
  containers:
  - name: main
    image: ellerbrock/alpine-bash-curl-ssl
    command: ["sleep", "9999999"]
  - name: ambassador
    image: ericshen90/kubectl-proxy:1.24.0
